#!/bin/sh
cp config/database.yml.sample config/database.yml
cp config/environments/production.rb.sample config/environments/production.rb
cp config/initializers/devise.rb.sample config/initializers/devise.rb
cp config/initializers/secret_token.rb.sample config/initializers/secret_token.rb
cp config/initializers/session_store.rb.sample config/initializers/session_store.rb

# change application name

# shell script references
# http://d.hatena.ne.jp/BigFatCat/20070807/1186461385

filepath=`pwd`
dir_name=`basename ${filepath}`

# change database.yml
default_db_name="rails3"
ruby -pi -e "gsub(/${default_db_name}/, '${dir_name}')" config/database.yml
echo "database.yml has been rewritted to ${dir_name}"

echo "Enter new application name: "
read application_name
default_name="Rails3"
echo "The application name is being changed to '${application_name}'..."

echo "Enter MySQL password: "
read password
ruby -pi -e "gsub(/password:/, 'password: ${password}')" config/database.yml
echo "MySQL password has been set."

ruby -pi -e "gsub(/${default_name}/, '${application_name}')" app/views/layouts/application.html.erb
ruby -pi -e "gsub(/${default_name}/, '${application_name}')" config.ru
ruby -pi -e "gsub(/${default_name}/, '${application_name}')" config/application.rb
ruby -pi -e "gsub(/${default_name}/, '${application_name}')" config/environment.rb
ruby -pi -e "gsub(/${default_name}/, '${application_name}')" config/environments/development.rb
ruby -pi -e "gsub(/${default_name}/, '${application_name}')" config/environments/production.rb
ruby -pi -e "gsub(/${default_name}/, '${application_name}')" config/environments/test.rb
ruby -pi -e "gsub(/${default_name}/, '${application_name}')" config/initializers/active_admin.rb
ruby -pi -e "gsub(/${default_name}/, '${application_name}')" config/initializers/secret_token.rb
ruby -pi -e "gsub(/${default_name}/, '${application_name}')" config/initializers/session_store.rb
ruby -pi -e "gsub(/${default_name}/, '${application_name}')" config/routes.rb
ruby -pi -e "gsub(/${default_name}/, '${application_name}')" Rakefile

echo "Application name has been changed to '${application_name}'."

echo "git submodule is being initialized..."
git submodule init
git submodule update

echo "Bundle install is being processed..."
bundle install
echo "Bundel install finished."

echo "Precompiling Assets may be needed for production"
# rake assets:precompile