require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RestsController do

  # This should return the minimal set of attributes required to create a valid
  # Rest. As you add validations to Rest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    if controller.current_user
      # car = controller.current_user.cars.last
      # driver = controller.current_user.drivers.last
      # report = FactoryGirl.create(:report, :car_id => car.id, :driver_id => driver.id)
      drivers = Driver.where(["user_id = ?", controller.current_user.id]).all
      driver = drivers[rand(drivers.size)]
      FactoryGirl.attributes_for(:rest, :report_id => driver.reports.last.id)
    else
      car = FactoryGirl.create(:car, :user_id => 100)
      driver = FactoryGirl.create(:driver, :user_id => 100)
      report = FactoryGirl.create(:report, :car_id => car.id, :driver_id => driver.id)
      FactoryGirl.attributes_for(:rest, :report_id => report.id)
    end
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RestsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  context "authenticated user" do
    signin_user

    describe "GET index" do
      it "assigns all rests as @rests" do
        rest = Rest.create! valid_attributes
        get :index, {}
        assigns(:rests).should eq([rest])
      end
    end

    describe "GET show" do
      it "assigns the requested rest as @rest" do
        rest = Rest.create! valid_attributes
        get :show, {:id => rest.to_param}
        assigns(:rest).should eq(rest)
      end
    end

    describe "GET new" do
      it "assigns a new rest as @rest" do
        get :new, {:report_id => FactoryGirl.create(:report).id}
        assigns(:rest).should be_a_new(Rest)
      end
    end

    describe "GET edit" do
      it "assigns the requested rest as @rest" do
        rest = Rest.create! valid_attributes
        get :edit, {:id => rest.to_param}
        assigns(:rest).should eq(rest)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new Rest" do
          expect {
            post :create, {:rest => valid_attributes}
          }.to change(Rest, :count).by(1)
        end

        it "assigns a newly created rest as @rest" do
          post :create, {:rest => valid_attributes}
          assigns(:rest).should be_a(Rest)
          assigns(:rest).should be_persisted
        end

        it "redirects to the report" do
          post :create, {:rest => valid_attributes}
          response.should redirect_to(Rest.last.report)
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved rest as @rest" do
          # Trigger the behavior that occurs when invalid params are submitted
          Rest.any_instance.stub(:save).and_return(false)
          post :create, {:rest => {}}
          assigns(:rest).should be_a_new(Rest)
        end

        it "re-renders the 'new' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          Rest.any_instance.stub(:save).and_return(false)
          post :create, {:rest => {}}
          response.should render_template("new")
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        it "updates the requested rest" do
          rest = Rest.create! valid_attributes
          # Assuming there are no other rests in the database, this
          # specifies that the Rest created on the previous line
          # receives the :update_attributes message with whatever params are
          # submitted in the request.
          Rest.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
          put :update, {:id => rest.to_param, :rest => {'these' => 'params'}}
        end

        it "assigns the requested rest as @rest" do
          rest = Rest.create! valid_attributes
          put :update, {:id => rest.to_param, :rest => valid_attributes}
          assigns(:rest).should eq(rest)
        end

        it "redirects to the reports index" do
          rest = Rest.create! valid_attributes
          put :update, {:id => rest.to_param, :rest => {:address => "another address"}}
          response.should redirect_to(report_path(rest.report))
        end
      end

      describe "with invalid params" do
        it "assigns the rest as @rest" do
          rest = Rest.create! valid_attributes
          # Trigger the behavior that occurs when invalid params are submitted
          Rest.any_instance.stub(:save).and_return(false)
          put :update, {:id => rest.to_param, :rest => {}}
          assigns(:rest).should eq(rest)
        end

        it "re-renders the 'edit' template" do
          rest = Rest.create! valid_attributes
          # Trigger the behavior that occurs when invalid params are submitted
          Rest.any_instance.stub(:save).and_return(false)
          put :update, {:id => rest.to_param, :rest => {}}
          response.should render_template("edit")
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested rest" do
        rest = Rest.create! valid_attributes
        expect {
          delete :destroy, {:id => rest.to_param}
        }.to change(Rest, :count).by(-1)
      end

      it "redirects to the rests list" do
        rest = Rest.create! valid_attributes
        delete :destroy, {:id => rest.to_param}
        response.should redirect_to(report_path(rest.report))
      end
    end
  end

  context "unauthenticated usef" do
    describe "GET index" do
      it "redirects to signin" do
        get :index, {}
        response.should redirect_to "/users/sign_in"
      end
    end

    describe "GET show" do
      it "redirect to signin" do
        rest = Rest.create! valid_attributes
        get :show, {:id => rest.to_param}
        response.should redirect_to "/users/sign_in"
      end
    end

    describe "GET new" do
      it "redirect to signin" do
        get :new, {}
        response.should redirect_to "/users/sign_in"
      end
    end

    describe "GET edit" do
      it "redirect to signin" do
        rest = Rest.create! valid_attributes
        get :edit, {:id => rest.to_param}
        response.should redirect_to "/users/sign_in"
      end
    end

    describe "POST create" do
      it "redirect to signin" do
        expect {
          post :create, {:rest => valid_attributes}
        }.to change(Rest, :count).by(0)
        response.should redirect_to "/users/sign_in"
      end
    end

    describe "PUT update" do
      it "redirect to signin" do
        # rest = FactoryGirl.build(:rest)
        # put :update, {:id => rest.to_param, :rest => {'these' => 'params'}}
        put :update, {:id => 1, :rest => {'these' => 'params'}}
        response.should redirect_to "/users/sign_in"
      end
    end

    describe "DELETE destroy" do
      it "redirects to signin" do
        # rest = FactoryGirl.build(:rest)
        # delete :destroy, {:id => rest.to_param}
        delete :destroy, {:id => 1}
        response.should redirect_to "/users/sign_in"
      end
    end
  end
end
