require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TransferSlipsController do

  # This should return the minimal set of attributes required to create a valid
  # TransferSlip. As you add validations to TransferSlip, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "report" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TransferSlipsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all transfer_slips as @transfer_slips" do
      transfer_slip = TransferSlip.create! valid_attributes
      get :index, {}, valid_session
      assigns(:transfer_slips).should eq([transfer_slip])
    end
  end

  describe "GET show" do
    it "assigns the requested transfer_slip as @transfer_slip" do
      transfer_slip = TransferSlip.create! valid_attributes
      get :show, {:id => transfer_slip.to_param}, valid_session
      assigns(:transfer_slip).should eq(transfer_slip)
    end
  end

  describe "GET new" do
    it "assigns a new transfer_slip as @transfer_slip" do
      get :new, {}, valid_session
      assigns(:transfer_slip).should be_a_new(TransferSlip)
    end
  end

  describe "GET edit" do
    it "assigns the requested transfer_slip as @transfer_slip" do
      transfer_slip = TransferSlip.create! valid_attributes
      get :edit, {:id => transfer_slip.to_param}, valid_session
      assigns(:transfer_slip).should eq(transfer_slip)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TransferSlip" do
        expect {
          post :create, {:transfer_slip => valid_attributes}, valid_session
        }.to change(TransferSlip, :count).by(1)
      end

      it "assigns a newly created transfer_slip as @transfer_slip" do
        post :create, {:transfer_slip => valid_attributes}, valid_session
        assigns(:transfer_slip).should be_a(TransferSlip)
        assigns(:transfer_slip).should be_persisted
      end

      it "redirects to the created transfer_slip" do
        post :create, {:transfer_slip => valid_attributes}, valid_session
        response.should redirect_to(reprot_path TransferSlip.last.report)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transfer_slip as @transfer_slip" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransferSlip.any_instance.stub(:save).and_return(false)
        post :create, {:transfer_slip => { "report" => "invalid value" }}, valid_session
        assigns(:transfer_slip).should be_a_new(TransferSlip)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransferSlip.any_instance.stub(:save).and_return(false)
        post :create, {:transfer_slip => { "report" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transfer_slip" do
        transfer_slip = TransferSlip.create! valid_attributes
        # Assuming there are no other transfer_slips in the database, this
        # specifies that the TransferSlip created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TransferSlip.any_instance.should_receive(:update_attributes).with({ "report" => "" })
        put :update, {:id => transfer_slip.to_param, :transfer_slip => { "report" => "" }}, valid_session
      end

      it "assigns the requested transfer_slip as @transfer_slip" do
        transfer_slip = TransferSlip.create! valid_attributes
        put :update, {:id => transfer_slip.to_param, :transfer_slip => valid_attributes}, valid_session
        assigns(:transfer_slip).should eq(transfer_slip)
      end

      it "redirects to the report" do
        transfer_slip = TransferSlip.create! valid_attributes
        put :update, {:id => transfer_slip.to_param, :transfer_slip => valid_attributes}, valid_session
        response.should redirect_to(report_path transfer_slip.report)
      end
    end

    describe "with invalid params" do
      it "assigns the transfer_slip as @transfer_slip" do
        transfer_slip = TransferSlip.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransferSlip.any_instance.stub(:save).and_return(false)
        put :update, {:id => transfer_slip.to_param, :transfer_slip => { "report" => "invalid value" }}, valid_session
        assigns(:transfer_slip).should eq(transfer_slip)
      end

      it "re-renders the 'edit' template" do
        transfer_slip = TransferSlip.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransferSlip.any_instance.stub(:save).and_return(false)
        put :update, {:id => transfer_slip.to_param, :transfer_slip => { "report" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transfer_slip" do
      transfer_slip = TransferSlip.create! valid_attributes
      expect {
        delete :destroy, {:id => transfer_slip.to_param}, valid_session
      }.to change(TransferSlip, :count).by(-1)
    end

    it "redirects to the report" do
      transfer_slip = TransferSlip.create! valid_attributes
      delete :destroy, {:id => transfer_slip.to_param}, valid_session
      response.should redirect_to(report_path transfer_slip.report)
    end
  end

end
